config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/index'

  resources :submit_requests do
    get 'inbox', on: :collection
    member do
      patch 'approve'
      patch 'reject'
    end
  end

  resources :tasks
  get 'relationships/create'

  get 'relationships/destroy'

  root 'top#index'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end


  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index,:show]

  devise_for :users,controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index,:show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  has_many :notifications ,dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @blog = @comment.blog
    @notification = @comment.notifications.build(user_id: @blog.user.id)

    respond_to do |format|
      if @comment.save
        format.html{redirect_to blog_path(@blog),notice:'コメントを投稿しました。'}
        format.json{render :show, status: :created, location: @comment}
        format.js{render :index}
        unless @comment.blog.user_id == current_user.id
          Pusher.trigger("user_#{@comment.blog.user_id}_channel", 'comment_created', {
            message: 'あなたの作成したブログにコメントが付きました'
          })
        end
        Pusher.trigger("user_#{@comment.blog.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.blog.user.id, read: false).count
        })
      else
        format.html{render :new}
        format.json{render json:@comment.errors,status: :unprocessable_entity}
      end
    end
  end

  def destroy
  @blog = Blog.find(params[:blog_id])
  @comment = current_user.comments.find_by(blog_id: @blog.id)


  respond_to do |format|
  @comment.destroy
  format.html{redirect_to blog_path(@blog),notice:'コメントを削除しました。'}
  format.json{render :show, status: :deleted, location: @comment}
  format.js{render :index}
  end
end

  private
  def comment_params
    params.require(:comment).permit(:blog_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([blog,comment],remote: true) do |f| %>
<%= f.error_messages! %>
<%= f.hidden_field :blog_id %>
<div class="field">
  <%= f.text_field :content, placeholder:"内容", class:"form-control" %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
  <% unless comment.id.nil? %>
  <li>
    <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
    <p class="left"><%= comment.content %></p>
    <% if current_user.id == comment.user.id %>
     <p class="right">
       <!-- <%= link_to '', edit_blog_comment_path(blog, comment),class: "fa fa-pencil-square-o fa-lg" %> -->
       <%= link_to '', blog_comment_path(blog, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data:{confirm: '本当に削除していいですか？'}%>
     </p>
    <% end %>
  </li>
  <% end %>
  <% end %>
</ul>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', {comments: @comment.blog.comments, blog: @comment.blog })%>")
$(':text').val('')