config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/index'

  resources :submit_requests do
    get 'inbox', on: :collection
    member do
      patch 'approve'
      patch 'reject'
    end
  end

  resources :tasks
  get 'relationships/create'

  get 'relationships/destroy'

  root 'top#index'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end


  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index,:show]

  devise_for :users,controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index,:show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,:omniauthable
  mount_uploader :avatar, AvatarUploader

  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :tasks, dependent: :destroy
  has_many :submit_requests, dependent: :destroy
  has_many :received_requests, class_name: 'SubmitRequest', foreign_key: 'request_user_id'

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
      name: auth.extra.raw_info.name,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
      image_url: auth.info.image,
      password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource =nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
      name: auth.info.nickname,
      image_url: auth.info.image,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
      password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"],current_user)

    if @user.persisted?
      set_flash_message(:notice,:success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind:"Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].expect("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
   hash[:uid] = User.create_unique_string
   super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @follower = @user.followers
    @followed_user = @user.followed_users
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.id == user.id %>
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large" %>
    <% end %>
  <% end %>
  <% end %>
</div>

app/views/users/_follow_index.html.erb
<h2><%= @user.name %>さんのページ</h2>
<div class="block col-md-10 col-sm-12 col-xs-12">
  <div class="following">
    <h3>フォロー</h3>
    <% @follower.each do |follow|%>
    <div class="followerlist">
      <div class="followerphoto">
        <%= profile_img(follow) %>
      </div>
      <div class="followername">
        <%= link_to follow.name, user_path(follow.id) %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="followed">
    <h3>フォロワー</h3>
    <% @followed_user.each do |followed|%>
    <div class="followedlist">
      <div class="followedphoto">
        <%= profile_img(followed) %>
      </div>
      <div class="followedname">
        <%= link_to followed.name, user_path(followed.id) %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー</h2>
  <% @users.each do |user| %>
    <div class="container-child col-md-2 col-sm-4 col-xs-6">
      <h3><%= link_to user.name, user_path(user.id) %></h3>
      <%= profile_img(user) %>
      <%= user.email %>
      <%= render 'follow_form', user: user %>
      <% if user.id != current_user.id %>
    <li class="userList">
      <div class="item">
        <!-- <%= link_to user.name, user %> -->
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
      </div>
      <!-- <%= render partial: 'follow_form', locals: { user: user } if signed_in?   %> -->
    </li>
  <% end %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<%= render 'follow_index' %>