config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/index'

  resources :submit_requests do
    get 'inbox', on: :collection
    member do
      patch 'approve'
      patch 'reject'
    end
  end

  resources :tasks
  get 'relationships/create'

  get 'relationships/destroy'

  root 'top#index'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end


  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index,:show]

  devise_for :users,controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index,:show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base

  belongs_to :user
  belongs_to :task
  belongs_to :request_user, class_name: 'User', foreign_key: 'request_user_id'

  validates :user_id, :task_id, :request_user_id, presence: true
  validate :no_repeated_request, on: :create

  private

  def no_repeated_request
   submit_request = SubmitRequest.where(task_id: task_id, status: 1)
   errors.add(:base, "このタスクは既に依頼をだしています。") unless submit_request.blank?
 end
end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy, :approve, :reject]

  def index
    @submit_requests = SubmitRequest.where(request_user_id: current_user.id).where(status: 1)
  end

  def show
  end

  def new
    @submit_request = current_user.submit_requests.build
  end

  def edit
  end

  def create
    @submit_request = current_user.submit_requests.build(submit_request_params)

    respond_to do |format|
      if @submit_request.save
        format.html { redirect_to @submit_request, notice: 'Submit request was successfully created.' }
        format.json { render :show, status: :created, location: @submit_request }
      else
        format.html { render :new }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @submit_request.update(submit_request_params)
        format.html { redirect_to @submit_request, notice: 'Submit request was successfully updated.' }
        format.json { render :show, status: :ok, location: @submit_request }
      else
        format.html { render :edit }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @submit_request.destroy
    respond_to do |format|
      format.html { redirect_to submit_requests_url, notice: 'Submit request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def inbox
  @submit_requests = SubmitRequest.where(request_user_id: current_user.id)
end

  def approve
    if @submit_request.update(submit_request_params)
      @submit_request.task.update(charge_id: current_user.id)
      redirect_to inbox_submit_requests_path, notice: '依頼を承認しました。'
    else
      redirect_to inbox_submit_requests_path, notice: '不具合が発生しました、もう一度操作を行ってください。'
    end
  end

  def reject
    if @submit_request.update(submit_request_params)
       redirect_to inbox_submit_requests_path, notice: '依頼を却下しました。'
    else
      redirect_to inbox_submit_requests_path, notice: '不具合が発生しました、もう一度操作を行ってください。'
    end
  end

  private
    def set_submit_request
      @submit_request = SubmitRequest.find(params[:id])
    end

    def submit_request_params
      params.require(:submit_request).permit(:user_id, :task_id, :message, :request_user_id, :status)
    end
end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
end

app/views/submit_requests/_form.html.erb
<%= form_for(@submit_request) do |f| %>
  <% if @submit_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submit_request.errors.count, "error") %> prohibited this submit_request from being saved:</h2>

      <ul>
      <% @submit_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% f.hidden_field :user_id %>

  <div class="container">
    <div class="row">
        <%= f.label "タスク" %> :
        <%= f.collection_select :task_id, Task.where(charge_id: current_user.id), :id, :title %>
    </div><br />

    <div class="row">
        <%= f.label "メッセージ" %>
        <%= f.text_area :message %>
    </div><br />

    <div class="row">
        <%= f.label "タスク依頼先" %>
        <%= f.collection_select :request_user_id, User.where.not(id: current_user.id), :id, :name %>
    </div><br />

    <div class="row">
        <%= f.label :状態 %> :
        <%= f.number_field :status %>
    </div><br />

    <div class="actions">
        <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/submit_requests/edit.html.erb
<h1>依頼タスク編集</h1>

<%= render 'form' %>

<%= link_to '編集', @submit_request %> |
<%= link_to '戻る', submit_requests_path %>

app/views/submit_requests/inbox.html.erb
<p id="notice"><%= notice %></p>

<h1>依頼タスク一覧</h1>
<div class="requestTaskTable">
  <table class="table table-striped table-bordered table-request table-responsive">
    <thead>
      <tr>
        <th>ユーザー</th>
        <th>タスク</th>
        <th>メッセージ</th>
        <th>依頼主</th>
        <th>状態</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @submit_requests.each do |submit_request| %>
        <tr>
          <td><%= submit_request.user.name %></td>
          <td><%= submit_request.task.title %></td>
          <td><%= submit_request.message %></td>
          <td><%= submit_request.request_user_id %></td>
          <td><%= submit_request.status %></td>
          <td><%= link_to '詳細', submit_request %></td>
          <td><%= link_to '承認する', approve_submit_request_path(submit_request, submit_request: {status: 2}), method: :patch, data: { confirm: '承認しますか?' } %></td>
          <td><%= link_to '却下する', reject_submit_request_path(submit_request, submit_request: {status: 9}), method: :patch, data: { confirm: '却下しますか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<br />

<%= link_to '新規タスク依頼', new_submit_request_path %>

app/views/submit_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>依頼タスク一覧</h1>
<div class="requestTaskTable">
  <table class="table table-striped table-bordered table-request table-responsive">
    <thead>
      <tr>
        <th>ユーザー</th>
        <th>タスク</th>
        <th>メッセージ</th>
        <th>依頼主</th>
        <th>状態</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @submit_requests.each do |submit_request| %>
        <tr>
          <td><%= submit_request.user.name %></td>
          <td><%= submit_request.task.title %></td>
          <td><%= submit_request.message %></td>
          <td><%= submit_request.request_user_id %></td>
          <td><%= submit_request.status %></td>
          <td><%= link_to '詳細', submit_request %></td>
          <td><%= link_to '編集', edit_submit_request_path(submit_request) %></td>
          <td><%= link_to '削除', submit_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<br>

<%= link_to '新規タスク依頼', new_submit_request_path %>

app/views/submit_requests/new.html.erb
<h1>新規タスク依頼</h1>

<%= render 'form' %>

<%= link_to '戻る', submit_requests_path %>

app/views/submit_requests/show.html.erb
<p id="notice"><%= notice %></p>
<h2>依頼タスク詳細</h2>
<p>
  <strong>ユーザー:</strong>
  <%= @submit_request.user.name %>
</p>

<p>
  <strong>タスク:</strong>
  <%= @submit_request.task.title %>
</p>

<p>
  <strong>メッセージ:</strong>
  <%= @submit_request.message %>
</p>

<p>
  <strong>依頼主:</strong>
  <%= @submit_request.request_user_id %>
</p>

<p>
  <strong>状態:</strong>
  <%= @submit_request.status %>
</p>

<%= link_to '編集', edit_submit_request_path(@submit_request) %> |
<%= link_to '戻る', submit_requests_path %>